config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get  '/users/fast', to: 'users/fast#show',               as: :user_fast
    put  '/users/fast', to: 'users/fast#quick_session',      as: :user_fast_session
    post '/users/fast', to: 'users/fast#quick_registration', as: :user_fast_registration
  end

  mount RailsAdmin::Engine, at: '/admin', as: 'rails_admin'
  mount Shopper::Engine, at: '/', as: 'shopper'

  resources :books, only: %i(show update)

  scope path: 'categories' do
    get '/',    to: 'categories#show', as: :categories
    get '/:id', to: 'categories#show', as: :category
  end

  namespace :settings do
    resource :address, only: %i(show update)
    resource :profile, only: %i(show update destroy), controller: 'profile'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    present HomePage::HomePresenter.new
  end
end

app/views/home/_carousel.html.haml
#slider.carousel.slide{ 'data-ride': "carousel"}
  %ol.carousel-indicators.general-carousel-indicators
    - books.each do |book|
      %li{class: book.active_class, 'data-target': "#slider", 'data-slide-to': book.index}
  .carousel-inner{ role: "listbox"}
    - books.each do |book|
      .item{class: book.active_class}
        .row
          .col-sm-5
            .general-img-wrap
              = image_tag book.cover, class: 'img-shadow general-thumbnail-img width-full'
          .col-sm-7
            .mb-60
              %h1= book.title
              %p.lead= book.description
              %p.in-grey-600.small= book.authors_names
              .general-align.pt-20
                = link_to t('.but_now'),
                  shopper.cart_add_product_path(type: book.product_type, id: book.id),
                  method: :post,
                  remote: true,
                  class: "btn btn-default #{book.disabled_class}"
  %a.left.carousel-control{ href: "#slider", role: "button", 'data-slide': "prev"}
    %span.icon-prev{ 'aria-hidden': "true"}
    %span.sr-only Previous
  %a.right.carousel-control{ href: "#slider", role: "button", 'data-slide': "next"}
    %span.icon-next{ 'aria-hidden': "true"}
    %span.sr-only Next

app/views/home/index.html.haml
= render partial: 'carousel', locals: { books: presenter.carousel_books }
.jumbotron.text-center.mb-0
  %h2.h1 Welcome to our amazing Bookstore!
  .mb-res-50
    %p.in-grey-600 We pore through hundreds of new books each month and select the five best we can find to share with our members.
  = link_to 'Get Started', categories_path, class: 'btn btn-default'
.mb-35
  %h3 Best Sellers
  - presenter.bestsellers.each_slice(4) do |slice|
    .row
      - slice.each do |bestseller|
        .col-sm-6.col-md-3
          = render partial: 'books/thumb', locals: { book: bestseller }